### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by Bidski** [meteorshowers/StereoNet-ActiveStereoNet#22]
I am trying to train the network and I am getting the following errors

```
Traceback (most recent call last):
  File "./main8Xmulti.py", line 22, in <module>
    from models.StereoNet8Xmulti import StereoNet
ModuleNotFoundError: No module named 'models.StereoNet8Xmulti'
```

Changing `from models.StereoNet8Xmulti import StereoNet` to `from models.StereoNet_single import StereoNet` fixes that error, but then I get this error

```
Traceback (most recent call last):
  File "./main8Xmulti.py", line 365, in <module>
    main()
  File "./main8Xmulti.py", line 170, in main
    train(TrainImgLoader, model, optimizer, log, epoch)
  File "./main8Xmulti.py", line 223, in train
    losses[idx].update(loss[idx].item() / args.loss_weights[idx])
IndexError: list index out of range
```

`loss` only has 2 elements in the list, but `losses` has 4. How can I fix this?

**Comment by ymk1933230135** [comment]
Hello, is the final output of this network a list? What do the two tensors in the list represent?

**Comment by yhzwy** [comment]
Hello, I got the same error as you.Have you solved that?

**Comment by Overture-Y** [comment]
I got the same error too, and after I changed  "from models.StereoNet8Xmulti import StereoNet " to "from models.StereoNet_single import StereoNet", the error became "exit 2", Have you solved that?
